@startuml
title RDCU pour redemarrerJeu

participant ":JeuDeDes" as JDD
participant "joueurs: \nMap<String, Joueur>" as joueurs

 -> JDD : redemarrerJeu()

note right of JDD 
selon Contrôleur 
(JeuDeDés est 
l'objet racine)
end note

JDD -> joueurs : clear()

note right of joueurs
selon Expert
end note

@enduml
